//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaidyakovTelenet
{
    using System;
    using System.Collections.Generic;
    
    public partial class CALL
    {
        public int CALL_ID { get; set; }
        public int CALLER_ID { get; set; }
        public string CALL_RECIPIENT_NUMBER { get; set; }
        public System.DateTime CALL_DATE { get; set; }
        public int CALL_DURATION { get; set; }
        public decimal CALL_COST { get; set; }
    
        public virtual PHONE_NUMBER PHONE_NUMBER { get; set; }
    }
}
