//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaidyakovTelenet
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public EMPLOYEE()
        {
            this.MAINTENANCE = new HashSet<MAINTENANCE>();
        }
    
        public int EMPLOYEE_ID { get; set; }
        public string EMPLOYEE_LAST_NAME { get; set; }
        public string EMPLOYEE_FIRST_NAME { get; set; }
        public string EMPLOYEE_PATRONYMIC { get; set; }
        public string EMPLOYEE_POSITION { get; set; }
        public string EMPLOYEE_EMAIL { get; set; }
        public string EMPLOYEE_STATUS { get; set; }
    
        public virtual ICollection<MAINTENANCE> MAINTENANCE { get; set; }
    }
}
