//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaidyakovTelenet
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPMENT
    {
        public EQUIPMENT()
        {
            this.MAINTENANCE = new HashSet<MAINTENANCE>();
        }
    
        public int EQUIPMENT_ID { get; set; }
        public Nullable<int> PHONE_ID { get; set; }
        public string EQUIPMENT_TYPE { get; set; }
        public string EQUIPMENT_MODEL { get; set; }
        public string EQUIPMENT_STATUS { get; set; }
        public System.DateTime EQUIPMENT_INSTALLATION_DATE { get; set; }
    
        public virtual PHONE_NUMBER PHONE_NUMBER { get; set; }
        public virtual ICollection<MAINTENANCE> MAINTENANCE { get; set; }
    }
}
