//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaidyakovTelenet
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAINTENANCE
    {
        public int WORK_ID { get; set; }
        public int EQUIPMENT_ID { get; set; }
        public int EMPLOYEE_ID { get; set; }
        public string WORK_TYPE { get; set; }
        public System.DateTime WORK_START_DATE { get; set; }
        public Nullable<System.DateTime> WORK_END_DATE { get; set; }
        public string WORK_RESULT { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual EQUIPMENT EQUIPMENT { get; set; }
    }
}
