//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaidyakovTelenet
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TelenetDBEntities : DbContext
    {
        public static TelenetDBEntities _context;

        public static TelenetDBEntities GetContext()
        {
            if (_context == null) _context = new TelenetDBEntities();
            return _context;
        }

        public TelenetDBEntities()
            : base("name=TelenetDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CALL> CALL { get; set; }
        public DbSet<EMPLOYEE> EMPLOYEE { get; set; }
        public DbSet<EQUIPMENT> EQUIPMENT { get; set; }
        public DbSet<MAINTENANCE> MAINTENANCE { get; set; }
        public DbSet<PAYMENT> PAYMENT { get; set; }
        public DbSet<PHONE_NUMBER> PHONE_NUMBER { get; set; }
        public DbSet<SERVICE> SERVICE { get; set; }
        public DbSet<SERVICE_REQUEST> SERVICE_REQUEST { get; set; }
        public DbSet<SUBSCRIBER> SUBSCRIBER { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TARIFF> TARIFF { get; set; }
    }
}
