//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaidyakovTelenet
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT
    {
        public int PAYMENT_ID { get; set; }
        public int SUBSCRIBER_ID { get; set; }
        public decimal PAYMENT_AMOUNT { get; set; }
        public System.DateTime PAYMENT_DATE { get; set; }
        public string PAYMENT_METHOD { get; set; }
        public string PAYMENT_STATUS { get; set; }
    
        public virtual SUBSCRIBER SUBSCRIBER { get; set; }
    }
}
