//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaidyakovTelenet
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONE_NUMBER
    {
        public PHONE_NUMBER()
        {
            this.CALL = new HashSet<CALL>();
            this.EQUIPMENT = new HashSet<EQUIPMENT>();
        }
    
        public int PHONE_ID { get; set; }
        public int SUBSCRIBER_ID { get; set; }
        public string PHONE_NUMBER1 { get; set; }
        public string PHONE_STATUS { get; set; }
        public System.DateTime PHONE_ACTIVATION_DATE { get; set; }
    
        public virtual ICollection<CALL> CALL { get; set; }
        public virtual ICollection<EQUIPMENT> EQUIPMENT { get; set; }
        public virtual SUBSCRIBER SUBSCRIBER { get; set; }
    }
}
