//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaidyakovTelenet
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUEST_TYPE
    {
        public REQUEST_TYPE()
        {
            this.SERVICE_REQUEST = new HashSet<SERVICE_REQUEST>();
        }
    
        public int REQUEST_TYPE_ID { get; set; }
        public string REQUEST_TYPE_NAME { get; set; }
    
        public virtual ICollection<SERVICE_REQUEST> SERVICE_REQUEST { get; set; }
    }
}
