//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaidyakovTelenet
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICE_REQUEST
    {
        public int REQUEST_ID { get; set; }
        public int SUBSCRIBER_ID { get; set; }
        public string REQUEST_TYPE { get; set; }
        public string REQUEST_DESCRIPTION { get; set; }
        public System.DateTime REQUEST_CREATION_DATE { get; set; }
        public string REQUEST_STATUS { get; set; }
    
        public virtual SUBSCRIBER SUBSCRIBER { get; set; }
    }
}
