//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaidyakovTelenet
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICE
    {
        public int SERVICE_ID { get; set; }
        public int TARIFF_ID { get; set; }
        public string SERVICE_NAME { get; set; }
        public string SERVICE_DESCRIPTION { get; set; }
        public decimal SERVICE_COST { get; set; }
    
        public virtual TARIFF TARIFF { get; set; }
    }
}
