//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaidyakovTelenet
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBSCRIBER
    {
        public SUBSCRIBER()
        {
            this.PAYMENT = new HashSet<PAYMENT>();
            this.PHONE_NUMBER = new HashSet<PHONE_NUMBER>();
            this.SERVICE_REQUEST = new HashSet<SERVICE_REQUEST>();
        }
    
        public int SUBSCRIBER_ID { get; set; }
        public string SUBSCRIBER_LASTNAME { get; set; }
        public string SUBSCRIBER_FIRSTNAME { get; set; }
        public string SUBSCRIBER_PATRONYMIC { get; set; }
        public string SUBSCRIBER_ADDRESS { get; set; }
        public System.DateTime SUBSCRIBER_CONNECTION_DATE { get; set; }
        public string SUBSCRIBER_STATUS { get; set; }
        public Nullable<int> SUBSCRIBER_TARIFF_ID { get; set; }
        public string subscriberFullName
        {
            get
            {
                string name = SUBSCRIBER_LASTNAME + ' ' + SUBSCRIBER_FIRSTNAME + ' ' + SUBSCRIBER_PATRONYMIC;
                return name;
            }
            set { }
        }
        public String _SUBSCRIBER_CONNECTION_DATE
        {
            get
            {
                String date = SUBSCRIBER_CONNECTION_DATE.ToString("dd.MM.yyyy");
                return date;
            }
            set { }
        }
        public String _SUBSCRIBER_TARIFF_NAME
        {
            get
            {
                String tariffName = "Не указан";
                if (SUBSCRIBER_TARIFF_ID != null)
                {
                    tariffName = TARIFF.TARIFF_NAME;
                }
                return tariffName;
            }
            set { }
        }

        public virtual ICollection<PAYMENT> PAYMENT { get; set; }
        public virtual ICollection<PHONE_NUMBER> PHONE_NUMBER { get; set; }
        public virtual ICollection<SERVICE_REQUEST> SERVICE_REQUEST { get; set; }
        public virtual TARIFF TARIFF { get; set; }
    }
}
