//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaidyakovTelenet
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBSCRIBER
    {
        public SUBSCRIBER()
        {
            this.PAYMENT = new HashSet<PAYMENT>();
            this.PHONE_NUMBER = new HashSet<PHONE_NUMBER>();
            this.SERVICE_REQUEST = new HashSet<SERVICE_REQUEST>();
            this.TARIFF = new HashSet<TARIFF>();
        }
    
        public int SUBSCRIBER_ID { get; set; }
        public string SUBSCRIBER_LASTNAME { get; set; }
        public string SUBSCRIBER_FIRSTNAME { get; set; }
        public string SUBSCRIBER_PATRONYMIC { get; set; }
        public string SUBSCRIBER_ADDRESS { get; set; }
        public System.DateTime SUBSCRIBER_CONNECTION_DATE { get; set; }
        public string SUBSCRIBER_STATUS { get; set; }
    
        public string subscriberFullName
        {
            get
            {
                string name = SUBSCRIBER_LASTNAME + ' ' + SUBSCRIBER_FIRSTNAME + ' ' + SUBSCRIBER_PATRONYMIC;
                return name;
            }
            set { }
        }
        public virtual ICollection<PAYMENT> PAYMENT { get; set; }
        public virtual ICollection<PHONE_NUMBER> PHONE_NUMBER { get; set; }
        public virtual ICollection<SERVICE_REQUEST> SERVICE_REQUEST { get; set; }
        public virtual ICollection<TARIFF> TARIFF { get; set; }
    }
}
