//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaidyakovTelenet
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBSCRIBER_BACKUP
    {
        public int SUBSCRIBER_ID { get; set; }
        public string SUBSCRIBER_LASTNAME { get; set; }
        public string SUBSCRIBER_FIRSTNAME { get; set; }
        public string SUBSCRIBER_PATRONYMIC { get; set; }
        public string SUBSCRIBER_ADDRESS { get; set; }
        public System.DateTime SUBSCRIBER_CONNECTION_DATE { get; set; }
        public string SUBSCRIBER_STATUS { get; set; }
    }
}
