//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaidyakovTelenet
{
    using System;
    using System.Collections.Generic;
    
    public partial class TARIFF
    {
        public TARIFF()
        {
            this.SERVICE = new HashSet<SERVICE>();
            this.SUBSCRIBER = new HashSet<SUBSCRIBER>();
        }
    
        public int TARIFF_ID { get; set; }
        public string TARIFF_NAME { get; set; }
        public decimal TARIFF_COST { get; set; }
        public string TARIFF_DESCRIPTION { get; set; }
        public int TARIFF_MINUTES_LIMIT { get; set; }
        public int TARIFF_DATA_LIMIT { get; set; }
    
        public virtual ICollection<SERVICE> SERVICE { get; set; }
        public virtual ICollection<SUBSCRIBER> SUBSCRIBER { get; set; }
    }
}
